### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by sheng-z** [shanzhenren/PLE#3]
Hi, Nice project! I have some questions regarding to the reproducibility.

I ran the pipeline using `./run.sh` (I changed the hyperparameters according to the instructions in this script.). 
Here is what I got:
#### For OntoNotes
```
Evaluate on test data...
Predicted labels (embedding):
prediction:9514, ground:9514
accuracy: 0.46766869876
macro_precision, macro_recall, macro_f1: 0.71447340761 0.590795143998 0.646774820366
micro_precision, micro_recall, micro_f1: 0.684940833959 0.515314774253 0.588141602293
```
#### For BBN
```
Evaluate on test data...
Predicted labels (embedding):
prediction:13276, ground:13276
accuracy: 0.641398011449
macro_precision, macro_recall, macro_f1: 0.813840398621 0.73504585342 0.77243891306
micro_precision, micro_recall, micro_f1: 0.695182970784 0.724010775481 0.709304081359
```

Looks like the experimental results in Table 9 in the paper are not reproducible, especially on the OntoNotes dataset. Do you have any insight about what's going on here?

#### For Wiki
Running the pipeline on Wiki seems to have a memory issue. I'm using the pre-compiled `hple` binary; at the stage of `Heterogeneous Partial-Label Embedding`, it quickly consumes all memory (16G Ram) on my machine. Here is the log:
```
Heterogeneous Partial-Label Embedding...
Mode: b
Reading nodes from file: Intermediate/Wiki/mention.txt, DONE!
Node size: 2669531
Node dims: 50
Reading nodes from file: Intermediate/Wiki/feature.txt, DONE!
Node size: 1913511
Node dims: 50
Reading nodes from file: Intermediate/Wiki/type.txt, DONE!
Node size: 128
Node dims: 50
Reading edges from file: Intermediate/Wiki/mention_feature.txt, DONE!
Edge size: 78770560
./run.sh: line 20: 19369 Killed                  Model/ple/hple -data $Data -mode bcd -size 50 -negatives 10 -iters 50 -threads 30 -lr 0.25 -alpha 0.0001
```

Look forward to your reply. Thanks in advance!

**Comment by shanzhenren** [comment]
hi @sheng-z , thanks for checking in. For hyperparameters of Ontonotes and BBN, I found the ones I put in run.sh were not the final ones we used. I have updated run.sh with correct parameters. And I suggest you re-run the pipeline several times since single run will have randomness due to the vector initialization.

For Wiki, the dataset is the largest so it will consume more memory. Not sure if this is a 32/64-bit issue but I suggest you try running on a 64 machine with larger memory and lower # of threads and see if it could work.
